### ISSUE TITLE
Image height and width not applied as transformation

### ISSUE THREAD

**Issue by CobyPear** [cupcakearmy/svelte-cloudinary#8]
Hello,
I've managed to get this library mostly working, however it seems that passing in `height` and `width` as `options` does not achieve the desired outcome.

**Expected**: Images are transformed, and the url from cloudinary shows the proper transformation
**Actual**: No transformation is applied when the image is fetched.

Here is what I'm getting back, note no `w_256` in the url: 
`"http://res.cloudinary.com/{Cloud Name}/image/upload/f_auto,q_auto/{image_name}"`

Here's my component:
```
 <img
    use:image={{
      src: 'image_name',
      options: {
        width: 256,
        height: 250,
      },
    }}
    alt="Logo"
  />
  ```
  
  Let me know if you need more information. Thanks for making this btw :)

**Comment by CobyPear** [comment]
Ah I just realized `crop` is necessary when using `height` and `width`, maybe it should be the default behavior? Are PRs welcome?

**Comment by cupcakearmy** [comment]
I see, I always used `bind` so probably never tested it 🤦 
Definetely should have a default value. If you want yo can make a PR, definetely welcomed.
Probably below here https://github.com/cupcakearmy/svelte-cloudinary/blob/32c828dee32cb6865b8692a1e0fc3f3605ce1be9/src/index.ts#L69

**Comment by cupcakearmy** [comment]
Should be online :)
